
version: '3.9'

services:
 nginx:
   image: nginx:latest
   container_name: nginx
   ports:
     - "80:80"
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   networks:
     - cardinalCloud
   depends_on:
    - cw-bff-service


 mqtt-mosquitto:
  container_name: mqtt-mosquitto
  image: eclipse-mosquitto:latest
  networks:
    - cardinalCloud
  ports:
    - "1883:1883"
  volumes:
    - ./mqtt-mosquitto/mqtt.conf:/mosquitto/config/mosquitto.conf

 cw_central_db:
  image: postgres:15
  container_name: cw_central_db
  networks:
    - cardinalCloud
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: cw_central_db
  volumes:
    - cw_central_db_data:/var/lib/postgresql/data
    - ./cw_central_db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  ports:
    - "5432:5432"

 cw_message_db:
  image: postgres:15
  container_name: cw_message_db
  networks:
    - cardinalCloud
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: cw_message_db
  volumes:
    - cw_message_db_data:/var/lib/postgresql/data
    - ./cw_message_db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  ports:
    - "5431:5431"
 
 cw-log-trace:
  container_name: cw-log-trace
  build:
   context: ./cw-log-trace
  networks:
    - cardinalCloud
  ports:
    - "5050:5050"

 cw-central-service:
  container_name: cw-central-service
  build:
   context: ./cw-central-service
  networks:
    - cardinalCloud
  ports:
    - "5001:5001"
  depends_on:
    - cw-log-trace
    - cw_central_db
    - cw-bff-service

 cw-bff-service:
  container_name: cw-bff-service
  build:
   context: ./cw-bff-service
  networks:
    - cardinalCloud
  ports:
    - "5004:5004"
  depends_on:
    - cw-log-trace
    - mqtt-mosquitto

 cw-message-service:
  container_name: cw-message-service
  build:
   context: ./cw-message-service
  networks:
   - cardinalCloud
  ports:
   - "5003:5003"
  depends_on:
   - cw-log-trace
   - mqtt-mosquitto
   - cw-mqtt-gateway
   - cw-bff-service

 cw-mqtt-gateway:
  container_name: cw-mqtt-gateway
  build:
   context: ./cw-mqtt-gateway
  networks:
    - cardinalCloud
  ports:
    - "5000:5000"
  depends_on:
    - cw-bff-service
    - cw-central-service
    - cw-log-trace
    - mqtt-mosquitto

networks:
 cardinalCloud:
  driver: bridge
  ipam:
   config:
     - subnet: 172.28.1.0/24

volumes:
  cw_central_db_data:
  cw_message_db_data:

